In [3]:
import pandas as pd
from pathlib import Path

## 2020 Player Information (Fantasy) - Pro Football Reference

In [4]:
url = 'https://www.pro-football-reference.com/years/2020/fantasy.htm'
df = pd.read_html(url)[0]
writepath = Path.cwd() / 'playerData2020.csv'
df.to_csv (writepath, index = False, header=True)
df.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player                 Tm            FantPos
0                  1    Derrick Henry *                TEN                 RB
1                  2     Alvin Kamara *                NOR                 RB
2                  3       Dalvin Cook*                MIN                 RB
3                  4     Davante Adams*                GNB                 WR
4                  5      Travis Kelce*                KAN                 TE

  Unnamed: 4_level_0 Games     Passing          ... Scoring           Fantasy  \
                 Age     G  GS     Cmp Att Yds  ...      TD  2PM  2PP  FantPt
0                 26    16  16       0   0   0  ...      17    1  NaN     314
1                 25    15  10       0   0   0  ...      21  NaN  NaN     295
2                 25    14  14       0   0   0  ...      17    3  NaN     294
3                 28    14  14       0   0   0  ...      18  NaN  NaN     243
4                 31    15  15       1   2   4  ...      11    1  NaN     208


     PPR   DKPt   FDPt  VBD PosRank OvRank
0  333.1  341.1  323.6  184       1      1
1  377.8  383.8  336.3  165       2      2
2  337.8  346.8  315.8  164       3      3
3  358.4  362.4  300.9  117       1      4
4  312.8  316.8  260.3  117       1      5

[5 rows x 33 columns]

## 2019 Player Information (Fantasy) - Pro Football Reference

In [5]:
url = 'https://www.pro-football-reference.com/years/2019/fantasy.htm'
df = pd.read_html(url)[0]
writepath = Path.cwd() / 'playerData2019.csv'
df.to_csv (writepath, index = False, header=True)
df.head()

  Unnamed: 0_level_0     Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Rk                 Player                 Tm
0                  1  Christian McCaffrey*+                CAR
1                  2        Lamar Jackson*+                BAL
2                  3        Derrick Henry *                TEN
3                  4            Aaron Jones                GNB
4                  5       Ezekiel Elliott*                DAL

  Unnamed: 3_level_0 Unnamed: 4_level_0 Games     Passing             ...  \
             FantPos                Age     G  GS     Cmp  Att   Yds  ...
0                 RB                 23    16  16       0    2     0  ...
1                 QB                 22    15  15     265  401  3127  ...
2                 RB                 25    15  15       0    0     0  ...
3                 RB                 25    16  16       0    0     0  ...
4                 RB                 24    16  16       0    0     0  ...

  Scoring           Fantasy
       TD  2PM  2PP  FantPt    PPR   DKPt   FDPt  VBD PosRank OvRank
0      19    1  NaN     355  471.2  477.2  413.2  215       1      1
1       7  NaN  NaN     416  415.7  429.7  421.7  152       1      2
2      18  NaN  NaN     277  294.6  303.6  285.6  136       2      3
3      19  NaN  NaN     266  314.8  322.8  290.3  125       3      4
4      14  NaN  NaN     258  311.7  319.7  284.7  117       4      5

[5 rows x 33 columns]

## 2018 Player Information (Fantasy) - Pro Football Reference

In [6]:
url = 'https://www.pro-football-reference.com/years/2018/fantasy.htm'
df = pd.read_html(url)[0]
writepath = Path.cwd() / 'playerData2018.csv'
df.to_csv (writepath, index = False, header=True)
df.head()

  Unnamed: 0_level_0   Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Rk               Player                 Tm
0                  1        Todd Gurley*+                LAR
1                  2      Saquon Barkley*                NYG
2                  3  Christian McCaffrey                CAR
3                  4       Alvin Kamara *                NOR
4                  5   Patrick Mahomes *+                KAN

  Unnamed: 3_level_0 Unnamed: 4_level_0 Games     Passing             ...  \
             FantPos                Age     G  GS     Cmp  Att   Yds  ...
0                 RB                 24    14  14       0    0     0  ...
1                 RB                 21    16  16       0    0     0  ...
2                 RB                 22    16  16       1    1    50  ...
3                 RB                 23    15  13       0    0     0  ...
4                 QB                 23    16  16     383  580  5097  ...

  Scoring           Fantasy
       TD  2PM  2PP  FantPt    PPR   DKPt   FDPt  VBD PosRank OvRank
0      21    3  NaN     313  372.1  379.1  342.6  178       1      1
1      15    1  NaN     295  385.8  391.8  340.3  159       2      2
2      13  NaN  NaN     279  385.5  392.5  332.0  143       3      3
3      18    3  NaN     273  354.2  360.2  313.7  138       4      4
4       2    1  NaN     417  417.1  437.1  429.1  134       1      5

[5 rows x 33 columns]

## 2017 Player Information (Fantasy) - Pro Football Reference

In [7]:
url = 'https://www.pro-football-reference.com/years/2017/fantasy.htm'
df = pd.read_html(url)[0]
writepath = Path.cwd() / 'playerData2017.csv'
df.to_csv (writepath, index = False, header=True)
df.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player                 Tm            FantPos
0                  1      Todd Gurley*+                LAR                 RB
1                  2     Le'Veon Bell*+                PIT                 RB
2                  3       Kareem Hunt*                KAN                 RB
3                  4     Alvin Kamara *                NOR                 RB
4                  5      Melvin Gordon                LAC                 RB

  Unnamed: 4_level_0 Games     Passing          ... Scoring           Fantasy  \
                 Age     G  GS     Cmp Att Yds  ...      TD  2PM  2PP  FantPt
0                 23    15  15       0   0   0  ...      19  NaN  NaN     319
1                 25    15  15       0   0   0  ...      11  NaN  NaN     257
2                 22    16  16       0   0   0  ...      11  NaN  NaN     242
3                 22    16   3       0   0   0  ...      14    1  NaN     239
4                 24    16  16       0   0   0  ...      12  NaN  NaN     230


     PPR   DKPt   FDPt  VBD PosRank OvRank
0  383.3  391.3  351.3  192       1      1
1  341.6  349.6  299.1  130       2      2
2  295.2  302.2  268.7  115       3      3
3  320.4  327.4  279.9  112       4      4
4  288.1  294.1  259.1  103       5      5

[5 rows x 33 columns]

## 2016 Player Information (Fantasy) - Pro Football Reference

In [8]:
url = 'https://www.pro-football-reference.com/years/2016/fantasy.htm'
df = pd.read_html(url)[0]
writepath = Path.cwd() / 'playerData2016.csv'
df.to_csv (writepath, index = False, header=True)
df.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player                 Tm            FantPos
0                  1    David Johnson*+                ARI                 RB
1                  2  Ezekiel Elliott*+                DAL                 RB
2                  3    Aaron Rodgers *                GNB                 QB
3                  4      LeSean McCoy*                BUF                 RB
4                  5      Le'Veon Bell*                PIT                 RB

  Unnamed: 4_level_0 Games     Passing             ... Scoring            \
                 Age     G  GS     Cmp  Att   Yds  ...      TD  2PM  2PP
0                 25    16  16       0    0     0  ...      20    1  NaN
1                 21    15  15       0    0     0  ...      16  NaN  NaN
2                 33    16  16     401  610  4428  ...       4    1    1
3                 28    15  15       0    0     0  ...      14    1  NaN
4                 24    12  12       0    1     0  ...       9    1  NaN

  Fantasy
   FantPt    PPR   DKPt   FDPt  VBD PosRank OvRank
0     328  407.8  416.8  367.8  191       1      1
1     293  325.4  332.4  309.4  156       2      2
2     380  380.0  397.0  387.0  119       1      3
3     248  298.3  304.3  273.3  111       3      4
4     242  317.4  324.4  279.9  105       4      5

[5 rows x 33 columns]

## 2015 Player Information (Fantasy) - Pro Football Reference

In [9]:
url = 'https://www.pro-football-reference.com/years/2015/fantasy.htm'
df = pd.read_html(url)[0]
writepath = Path.cwd() / 'playerData2015.csv'
df.to_csv (writepath, index = False, header=True)
df.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                  Rk             Player                 Tm            FantPos
0                  1   Antonio Brown *+                PIT                 WR
1                  2  Devonta Freeman *                ATL                 RB
2                  3     Julio Jones *+                ATL                 WR
3                  4  Adrian Peterson*+                MIN                 RB
4                  5       Cam Newton*+                CAR                 QB

  Unnamed: 4_level_0 Games     Passing             ... Scoring            \
                 Age     G  GS     Cmp  Att   Yds  ...      TD  2PM  2PP
0                 27    16  16       0    0     0  ...      11    2  NaN
1                 23    15  13       0    0     0  ...      14  NaN  NaN
2                 26    16  16       0    0     0  ...       9  NaN  NaN
3                 30    16  16       0    0     0  ...      11  NaN  NaN
4                 26    16  16     296  495  3837  ...      10  NaN  NaN

  Fantasy
   FantPt    PPR   DKPt   FDPt  VBD PosRank OvRank
0     252  388.2  393.2  320.2  125       1      1
1     243  316.4  324.4  279.9  123       1      2
2     239  375.1  379.1  307.1  111       2      3
3     231  260.7  269.7  245.7  110       2      4
4     389  389.1  409.1  399.1  105       1      5

[5 rows x 33 columns]